baseURL: "https://vsslog.dev/"
languageCode: "en-us"
title: "Vss Log"
theme: "PaperMod"
paginate: 5
enableRobotsTXT: true
enableEmoji: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production
  title: Vss
  description: "Personal website for Vikas Shetty"

  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  GoogleAnalyticsID: G-V0ZH6RS2BM
  disableSpecial1stPost: false
  comments: false
  hidemeta: false
  showtoc: false
  tocopen: false
  assets:
    favicon: icons/favicon.ico
    favicon16x16: icons/favicon-16x16.png
    favicon32x32: icons/favicon-32x32.png
    apple_touch_icon: icons/apple-touch-icon.png
    android-chrome: icons/android-chrome-512x512.png
    disableHLJS: true
  label:
    text: Vss's log
  homeInfoParams:
    Title: "Hi there! \U0001F44B"
    Content: |
      - Welcome to my website!. This is the right place to discover more about me if you're interested. I share my thoughts, opinions and experiences as a developer.
      -
      - I used to run a site called Digispectra which basically covered TV shows, new tech and games.
      So the idea behind this particular blog is to cover a wider plethora of topics and being an outlet for my brain :)
      
  socialIcons:
  - name: twitter
    url: https://twitter.com/@vikas_sshetty
  - name: github
    url: https://github.com/vss96
  - name: medium
    url: https://medium.com/@vikassshetty
  - name: instagram
    url: https://www.instagram.com/vikas_sshetty/
  - name: linkedin
    url: https://www.linkedin.com/in/vikas-shetty-456b73114/
  - name: email
    url: mailto:shettyvikas209@gmail.com
  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: false
    linkFullImages: true
menu:
  main:
  - name: About
    identifier: about
    url: about/
    weight: 1
  - name: Blog
    identifier: blog
    url: blog/
    weight: 2

markup:
  highlight:
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # noClasses: false
    # style: "borland"
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineNos: true
    lineNumbersInTable: true
    noClasses: true
    style: native
